/// @description PRESENTS!
GIFTED = false;
START_SPURT = false;
SPURT_FREQUENCY = GAMESPEED div 2;
//FRIEND_ID = choose(FRIENDS.CHIPMUNK_GIRL, FRIENDS.CHIPMUNK_BOY, FRIENDS.CAT_BOY, FRIENDS.CAT_GIRL);
image_speed = 0;
image_index = 0;

