/// @description DRAWS WHICH ITEMS THE PLAYER HAS ON THE SCREEN


if (RED_KEY_COLLECTED) {
	// DRAW THE RED KEY'S SPRITE
}
if (GREEN_KEY_COLLECTED) {
	// DRAW THE GREEN KEY'S SPRITE
}
if (BLUE_KEY_COLLECTED) {
	// DRAW THE BLUE KEY'S SPRITE	
}
// DRAW SPRITES FOR OTHER KEY ITEMS 