/// @description START OF TURN
if (TESTING) {show_debug_message("TURN STARTED");}

var MATCH_ENDED = false;
var OTHER_PLAYER = (CURRENT_TURN == PLAYERS.PLAYER_1) ? PLAYERS.PLAYER_2 : PLAYERS.PLAYER_1;

////CHECK IF THE PLAYER CAN NO LONGER MAKE VALID MOVES
////FIRST PLAYER WHO CAN'T MAKE A VALID MOVE LOSES
if ( !AnyValidLogs(CURRENT_TURN) ) { 
	MATCH_ENDED = true; 
	MATCH_WINNER = OTHER_PLAYER;
}

if (MATCH_ENDED) {
	//PERFORM MATCH END EVENT
	event_perform(ev_other, ev_user2);
}