/// @description MATCH END

if (MATCH_STATE == MATCH_STAGE.MATCH_END) {exit;}

if (MATCH_WINNER == PLAYERS.PLAYER_1) { PLAYER_1_SCORE++; with (PLAYER_2_OBJ) {CAN_DIE = true;} }

if (MATCH_WINNER == PLAYERS.PLAYER_2) { PLAYER_2_SCORE++; with (PLAYER_1_OBJ) {CAN_DIE = true;} }

// PERHAPS MAKE THIS AN EASTER EGG?
play_sfx(sfxFinishHer);

MATCH_STATE = MATCH_STAGE.MATCH_END;