/// @description ON LEVEL CLEAR, LETS YOU RETURN TO MAP

ENABLED = DEFAULT_ENABLED_STATE;
DESTINATION = SPECIALROOMS.LEVEL_SELECT;
WORLD = 0; // IF DESTINATION == SPECIALROOMS.LEVEL_SELECT, USE THIS VARIABLE TO FIGURE OUT WHICH LEVEL SELECT TO RETURN TO?